"""Presigned URL compatibility tests.

Validates the query-auth branch of the SigV4 verifier by serving presigned
URLs: both ones generated by boto3 (real client behaviour) and ones generated
by Minamo's own helper.
"""
from __future__ import annotations

from minamo.api.presign import build_presigned_url
from minamo.config import Settings


def test_boto3_presigned_get(s3, raw):
    b = "presign-bucket"
    s3.create_bucket(Bucket=b)
    s3.put_object(Bucket=b, Key="secret.txt", Body=b"topsecret")

    url = s3.generate_presigned_url(
        "get_object", Params={"Bucket": b, "Key": "secret.txt"}, ExpiresIn=300
    )
    # Use the raw HTTP client so no SigV4 signature is attached.
    resp = raw.get(url)
    assert resp.status_code == 200
    assert resp.content == b"topsecret"


def test_minamo_generated_presigned_get(s3, raw, server):
    b = "presign-bucket-2"
    s3.create_bucket(Bucket=b)
    s3.put_object(Bucket=b, Key="k.txt", Body=b"payload")

    settings = Settings(
        access_key="minamo", secret_key="minamo-secret", region="us-east-1"
    )
    url = build_presigned_url(server, settings, b, "k.txt", expires=300, method="GET")
    resp = raw.get(url)
    assert resp.status_code == 200
    assert resp.content == b"payload"
